name: Confluence Publisher
description: Publishes Markdown docs to Confluence.
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
      run: python .github/actions/confluence-publisher/entrypoint.py
      run: python entrypoint.py
      shell: bash
            env:
              CONFLUENCE_URL: ${{ env.CONFLUENCE_URL }}
              CONFLUENCE_USER: ${{ env.CONFLUENCE_USER }}
        CONFLUENCE_API_TOKEN: ${{ env.CONFLUENCE_API_TOKEN }}
      # Ensure the following environment variables are set in your workflow or repository secrets:
      #   - CONFLUENCE_URL
      #   - CONFLUENCE_USER
      #   - CONFLUENCE_API_TOKEN
