runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies and publish to Confluence
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python .github/actions/confluence-publisher/entrypoint.py
      shell: bash
      env:
        CONFLUENCE_URL: ${{ env.CONFLUENCE_URL }}
        CONFLUENCE_USER: ${{ env.CONFLUENCE_USER }}
        CONFLUENCE_API_TOKEN: ${{ env.CONFLUENCE_API_TOKEN }}