name: Publish Docs to Confluence

on:
  push:
    branches:
      - main # Or whatever your primary branch is
      - feature/** # Optional: include nested feature branches if needed
      - feature/** # Optional: include nested feature branches if needed
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pyyaml python-frontmatter jinja2 markdown-it-py mdit-py-plugins

      - name: Run Confluence Publisher
        uses: ./.github/actions/confluence-publisher # Use an explicit version tag or commit SHA
        env:
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }} # Make sure this secret is defined in your repository/organization settings
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }} # Ensure this secret exists in your repository/organization settings
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }} # Ensure this secret exists in your repository/organization settings